### ISSUE TITLE
yapılan movie projesini uml'inin  github wikiye eklenmesi

### ISSUE THREAD

**Issue by ackepenek** [hilaltanriverdi/Movie#2]
Çok basit haliyle projenin uml diagramını wikiye eklensin. Diagram çizme toolu bulamasanız bile şu entityler var entitylerin şu alanları var. Birden fazla entity varsa birbiriyle şu ilişkiyle bağlı(onetoone, manytoone, manytomany) bağlı şeklinde gibi de yazabilirsiniz.

wiki:
https://github.com/tnrvrd/Movie/wiki

**Comment by hilaltanriverdi** [comment]
entity bilgilerini wikiye ekledim
