### ISSUE TITLE
arayüz geliştirmeleri

### ISSUE THREAD

**Issue by ackepenek** [hilaltanriverdi/Movie#4]
- [x] Film ekleme
- [x] Film silme
- [x] Film düzenleme
- [x] Film listeleme
- [x] Film beğenme

**Comment by hilaltanriverdi** [comment]
Film begeni metotları eklenecek.

**Comment by hilaltanriverdi** [comment]
Kullanıcıların film begenisi yapabilecegi butonlar konuldu ve metotlar oluşturuldu.
