### ISSUE TITLE
kullanıcı entity'sinin oluşturulması ve kimlik kanıtlamasının yapılması

### ISSUE THREAD

**Issue by ackepenek** [hilaltanriverdi/Movie#5]
Sisteme kullanıcı adı ve parolasını girip ve sistem tarafından doğrulanan kişilerin girebilmesi ve işlem yapması gerekmektedir.

**Comment by ackepenek** [comment]
ilişkili commit: https://github.com/hilaltanriverdi/Movie/commit/cc2fbbc1e565df9c2c79307a0335b83c7ef5f6cc

**Comment by hilaltanriverdi** [comment]
Kullanıcı entity si oluşturuldu, Entity alanları: userId, UserName, Password.
 kimlik kanıtlaması yapılacak.

**Comment by hilaltanriverdi** [comment]
Spring security kullanılarak sadece kayıtlı kullanıcıların sisteme giriş yapabilmesi saglandı.
